name: DS TP Automatisation 
on: [push]  
  
permissions:   
  contents: write  

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest      
    
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Définir la date
        id: date
        run: echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        
      - name: créer Q4_archive_date.txt          
        run : |
          echo "Evan CNAEPELNICKX" > Q4_archive_date.txt
          cat Q4.java >> Q4_archive_date.txt
          echo ${DATE} >> Q4_archive_date.txt
      
      - name: commit et push du fichier         
        run: |           
          git config --global user.name "evanIUT"           
          git config --global user.email "evancnaepelnickx@gmail.com"           
          git add Q2_archive_TOTO.txt            
          git commit -m "Création du fichier Q2_archive_TOTO.txt"           
          git push
